Exception ignored in: <generator object DataLoaderShard.__iter__ at 0x7fe5266e23c0>
Traceback (most recent call last):
  File "/home/robertthomas/miniconda3/envs/demucsRiley/lib/python3.9/site-packages/accelerate/data_loader.py", line 463, in __iter__
    yield current_batch
KeyboardInterrupt:
Traceback (most recent call last):
  File "/home/robertthomas/rileyProject/demucs/new_trainer.py", line 248, in <module>
    losses = estimate_loss()
  File "/home/robertthomas/miniconda3/envs/demucsRiley/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/robertthomas/rileyProject/demucs/new_trainer.py", line 200, in estimate_loss
    f1, f1_w_vel = f1_score(onset, onset_pred, velocity, velocity_pred)
  File "/home/robertthomas/rileyProject/demucs/metrics.py", line 65, in f1_score
    f1_score = mir_eval.onset.f_measure(reference_onsets, estimated_onsets)
  File "/home/robertthomas/miniconda3/envs/demucsRiley/lib/python3.9/site-packages/mir_eval/onset.py", line 93, in f_measure
    matching = util.match_events(reference_onsets, estimated_onsets, window)
  File "/home/robertthomas/miniconda3/envs/demucsRiley/lib/python3.9/site-packages/mir_eval/util.py", line 708, in match_events
    matching = sorted(_bipartite_match(G).items())
  File "/home/robertthomas/miniconda3/envs/demucsRiley/lib/python3.9/site-packages/mir_eval/util.py", line 587, in _bipartite_match
    pred = dict([(u, unmatched) for u in graph])
  File "/home/robertthomas/miniconda3/envs/demucsRiley/lib/python3.9/site-packages/mir_eval/util.py", line 587, in <listcomp>
    pred = dict([(u, unmatched) for u in graph])
KeyboardInterrupt